# Generated by Django 5.1.6 on 2025-04-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuvote',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuVote',
        ),
    ]
